/**
 * This file is automatically generated by GenerateTest.py, collecting function
 * information from source files.
 *
 * If you want to change the content of this file, go to GenerateTest.py and
 * modify the script. Or you can maintain this file by yourself after you delete
 * the related lines in the makefile.
 */

#include "Test.h"

int (*tests[])() = {
	testAdamsPECE,
	testAdaptiveSimpson,
	testBisection,
	testChasing,
	testClassicRK,
	testDividedDiff,
	testGaussianEli,
	testGaussianEliPP,
	testHermiteIpl,
	testLeastSq,
	testMuller,
	testNewtonMethod,
	testPicardRecurtion,
	testQR,
	testRKF,
	testRomberg,
	testSecent,
	testSODERungeKutta,
	testSplineIpl,
	testSteffensen
};

char *names[] = {
	"testAdamsPECE",
	"testAdaptiveSimpson",
	"testBisection",
	"testChasing",
	"testClassicRK",
	"testDividedDiff",
	"testGaussianEli",
	"testGaussianEliPP",
	"testHermiteIpl",
	"testLeastSq",
	"testMuller",
	"testNewtonMethod",
	"testPicardRecurtion",
	"testQR",
	"testRKF",
	"testRomberg",
	"testSecent",
	"testSODERungeKutta",
	"testSplineIpl",
	"testSteffensen"
};

int num = 20;
