/*
** This file is automatically generated by GenerateTest.py.
*/

#ifndef _TESTDECLARATION_H_
#define _TESTDECLARATION_H_

#define PASSED 0
#define FAILED 1

extern int (*tests[])();
extern char *names[];

int testAdaptiveSimpson();
int testSODERungeKutta();
int testMuller();
int testClassicRK();
int testHermiteIpl();
int testRKF();
int testBisection();
int testSecent();
int testLeastSq();
int testPicardRecurtion();
int testGaussianEli();
int testSplineIpl();
int testDividedDiff();
int testAdamsPECE();
int testQR();
int testChasing();
int testSteffensen();
int testNewtonMethod();
int testRomberg();
int testall();

#endif
