/*
** This file is automatically generated by GenerateTest.py.
*/

#ifndef _TESTDECLARATION_H_
#define _TESTDECLARATION_H_

#define PASSED 0
#define FAILED 1
int testAdaptiveSimpson();
int testRomberg();
int testChasing();
int testSplineIpl();
int testHermiteIpl();
int testGaussianEli();
int testClassicRK();
int testAdamsPECE();
int testRKF();
int testSODERungeKutta();
int testLeastSq();
int testQR();
int testBisection();
int testPicardRecurtion();
int testSteffensen();
int testNewtonMethod();
int testSecent();
int testDividedDiff();
int testMuller();
int testall();

#endif
