/*
** This file is automatically generated by GenerateTest.py.
*/
#ifndef _TI_H_
#define _TI_H_

#include "Test.h"

int (*tests[])() = {
	testAdaptiveSimpson,
	testRomberg,
	testChasing,
	testSplineIpl,
	testHermiteIpl,
	testGaussianEli,
	testClassicRK,
	testAdamsPECE,
	testRKF,
	testSODERungeKutta,
	testLeastSq,
	testQR,
	testBisection,
	testPicardRecurtion,
	testSteffensen,
	testNewtonMethod,
	testSecent,
	testDividedDiff,
	testMuller
};

char *names[] = {
	"testAdaptiveSimpson",
	"testRomberg",
	"testChasing",
	"testSplineIpl",
	"testHermiteIpl",
	"testGaussianEli",
	"testClassicRK",
	"testAdamsPECE",
	"testRKF",
	"testSODERungeKutta",
	"testLeastSq",
	"testQR",
	"testBisection",
	"testPicardRecurtion",
	"testSteffensen",
	"testNewtonMethod",
	"testSecent",
	"testDividedDiff",
	"testMuller"
};

#endif
