/*
** This file is automatically generated by GenerateTest.py.
*/
#include "Test.h"

int (*tests[])() = {
	testAdamsPECE,
	testAdaptiveSimpson,
	testBisection,
	testChasing,
	testClassicRK,
	testDividedDiff,
	testGaussianEli,
	testHermiteIpl,
	testLeastSq,
	testMuller,
	testNewtonMethod,
	testPicardRecurtion,
	testQR,
	testRKF,
	testRomberg,
	testSODERungeKutta,
	testSecent,
	testSplineIpl,
	testSteffensen
};

char *names[] = {
	"testAdamsPECE",
	"testAdaptiveSimpson",
	"testBisection",
	"testChasing",
	"testClassicRK",
	"testDividedDiff",
	"testGaussianEli",
	"testHermiteIpl",
	"testLeastSq",
	"testMuller",
	"testNewtonMethod",
	"testPicardRecurtion",
	"testQR",
	"testRKF",
	"testRomberg",
	"testSODERungeKutta",
	"testSecent",
	"testSplineIpl",
	"testSteffensen"
};
int num = sizeof(tests) / sizeof(int (*)());